### ISSUE TITLE
Alloy smeltery side config broken

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#58]
Trying to configure an alloy smeltery to receive energy from the side fails. Only bottom works. Side config seems to be broken

**Comment by Pokemonplatin** [comment]
Not reproduceable on Server 
![image](https://user-images.githubusercontent.com/11477613/78656488-c2c90380-78c7-11ea-8113-c8430c351842.png)

**Comment by Cydhra** [comment]
Sorry, duplicate to #60
